apiVersion: v1
kind: ConfigMap
metadata:
  name: student-card-config
data:
  STUDENT_FULL_NAME: "BLANK"
  STUDENT_GROUP: "BLANK"
  STUDENT_INSTITUTE: "BLANK"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"